import { IBoardState } from "../types/IBoardState";

export const  initialBoardState: IBoardState = [
    {position: 'A1', tile:'rD', userTile : true},
    {position: 'B1', tile:'kL', userTile: true},
    {position: 'C1', tile:'bD', userTile: true},
    {position: 'D1', tile:'Q', userTile: true},
    {position: 'E1', tile:'K', userTile: true},
    {position: 'F1', tile:'bL', userTile: true},
    {position: 'G1', tile:'kD', userTile: true},
    {position: 'H1', tile:'rL', userTile: true},
    {position: 'A2', tile:'rDp', userTile: true},
    {position: 'B2', tile:'kLp', userTile: true},
    {position: 'C2', tile:'bDp', userTile: true},
    {position: 'D2', tile:'Qp', userTile: true},
    {position: 'E2', tile:'Kp', userTile: true},
    {position: 'F2', tile:'bLp', userTile: true},
    {position: 'G2', tile:'kDp', userTile: true},
    {position: 'H2', tile:'rLp', userTile: true},
    {position: 'A3', },
    {position: 'B3', },
    {position: 'C3', },
    {position: 'D3', },
    {position: 'E3', },
    {position: 'F3', },
    {position: 'G3', },
    {position: 'H3', },
    {position: 'A4', },
    {position: 'B4', },
    {position: 'C4', },
    {position: 'D4', },
    {position: 'E4', },
    {position: 'F4', },
    {position: 'G4', },
    {position: 'H4', },
    {position: 'A5', },
    {position: 'B5', },
    {position: 'C5', },
    {position: 'D5', },
    {position: 'E5', },
    {position: 'F5', },
    {position: 'G5', },
    {position: 'H5', },
    {position: 'A6', },
    {position: 'B6', },
    {position: 'C6', },
    {position: 'D6', },
    {position: 'E6', },
    {position: 'F6', },
    {position: 'G6', },
    {position: 'H6', },
    {position: 'A7', tile:'rLp' , userTile: false},
    {position: 'B7', tile:'kDp' , userTile: false},
    {position: 'C7', tile:'bLp' , userTile: false},
    {position: 'D7', tile:'Q' , userTile: false},
    {position: 'E7', tile:'K' , userTile: false},
    {position: 'F7', tile:'bDp' , userTile: false},
    {position: 'G7', tile:'kLp' , userTile: false},
    {position: 'H7', tile:'rDp' , userTile: false},
    {position: 'A8', tile:'rL' , userTile: false},
    {position: 'B8', tile:'kD' , userTile: false},
    {position: 'C8', tile:'bL' , userTile: false},
    {position: 'D8', tile:'Q' , userTile: false},
    {position: 'E8', tile:'K' , userTile: false},
    {position: 'F8', tile:'bD' , userTile: false},
    {position: 'G8', tile:'kL' , userTile: false},
    {position: 'H8', tile:'rD' , userTile: false},
]