import { IBoardState } from "../types/IBoardState";

export const  initialBoardState: IBoardState = [
    {position: 'A1', tileType:'rD', userTile : true},
    {position: 'B1', tileType:'kL', userTile: true},
    {position: 'C1', tileType:'bD', userTile: true},
    {position: 'D1', tileType:'Q', userTile: true},
    {position: 'E1', tileType:'K', userTile: true},
    {position: 'F1', tileType:'bL', userTile: true},
    {position: 'G1', tileType:'kD', userTile: true},
    {position: 'H1', tileType:'rL', userTile: true},
    {position: 'A2', tileType:'rDp', userTile: true},
    {position: 'B2', tileType:'kLp', userTile: true},
    {position: 'C2', tileType:'bDp', userTile: true},
    {position: 'D2', tileType:'Qp', userTile: true},
    {position: 'E2', tileType:'Kp', userTile: true},
    {position: 'F2', tileType:'bLp', userTile: true},
    {position: 'G2', tileType:'kDp', userTile: true},
    {position: 'H2', tileType:'rLp', userTile: true},
    {position: 'A3', },
    {position: 'B3', },
    {position: 'C3', },
    {position: 'D3', },
    {position: 'E3', },
    {position: 'F3', },
    {position: 'G3', },
    {position: 'H3', },
    {position: 'A4', },
    {position: 'B4', },
    {position: 'C4', },
    {position: 'D4', },
    {position: 'E4', },
    {position: 'F4', },
    {position: 'G4', },
    {position: 'H4', },
    {position: 'A5', },
    {position: 'B5', },
    {position: 'C5', },
    {position: 'D5', },
    {position: 'E5', },
    {position: 'F5', },
    {position: 'G5', },
    {position: 'H5', },
    {position: 'A6', },
    {position: 'B6', },
    {position: 'C6', },
    {position: 'D6', },
    {position: 'E6', },
    {position: 'F6', },
    {position: 'G6', },
    {position: 'H6', },
    {position: 'A7', tileType:'rLp' , userTile: false},
    {position: 'B7', tileType:'kDp' , userTile: false},
    {position: 'C7', tileType:'bLp' , userTile: false},
    {position: 'D7', tileType:'Q' , userTile: false},
    {position: 'E7', tileType:'K' , userTile: false},
    {position: 'F7', tileType:'bDp' , userTile: false},
    {position: 'G7', tileType:'kLp' , userTile: false},
    {position: 'H7', tileType:'rDp' , userTile: false},
    {position: 'A8', tileType:'rL' , userTile: false},
    {position: 'B8', tileType:'kD' , userTile: false},
    {position: 'C8', tileType:'bL' , userTile: false},
    {position: 'D8', tileType:'Q' , userTile: false},
    {position: 'E8', tileType:'K' , userTile: false},
    {position: 'F8', tileType:'bD' , userTile: false},
    {position: 'G8', tileType:'kL' , userTile: false},
    {position: 'H8', tileType:'rD' , userTile: false},
]